// a = entree
// b = drink
// c = sides
// d = snacks
// e = specials

let items = {
ba: ['Aquafina 20oz',1.75],
bb: ['Arizona',2],
bc: ['Arnold Palmer',2.5],
bd: ['Bubbly',1.5],
be: ['Coffee',1.95],
bg: ['Cold Brew',4.5],
bh: ['Frappacino',4],
bi: ['Gatorade',2.75],
bj: ['Iced Coffee',2.95],
bk: ['Izze',2.25],
bl: ['Kickstart',3],
bm: ['Lifewater',2.25],
bn: ['Milk Pint',1],
bo: ['Naked',4],
bp: ['Naked Small',3],
bq: ['Nestle Water',1.25],
br: ['Propel',2.75],
bs: ['Pure Leaf',2.25],
bt: ['Skinny Pop',1.75],
bu: ['Small Water',0.5],
bv: ['Smoothie',3.5],
bw: ['Soda 20 oz',2],
bx: ['Soda Can',1.5],
by: ['Soy Milk',2.5],
bz: ['Tropicana Juice',2.75],
baa: ['Water',1],
daj: ['Apple Fritter',2.5],
ab: ['12 oz Soup',2.5],
ac: ['2 Tacos',5],
ad: ['6" Sub',5.25],
ae: ['8 oz Soup',1.75],
af: ['Bagel',1.75],
ag: ['Breakfast Burrito',3.5],
ah: ['Breakfast Sandwich',2.5],
ai: ['Breakfast Sandwich Meat',2.75],
aj: ['Breakfast Special',3],
ak: ['Burrito/Burrito Bowl',5.25],
al: ['Calzone',4],
am: ['Cheeseburger',4],
an: ['Croissant',2],
ao: ['Danish',2.25],
ap: ['Deli Sandwich',4.95],
aq: ['Donut/Pastries',1.65],
ar: ['French Toast',1.55],
as: ['French Toast Sticks',1.55],
at: ['Fried Rice',3],
au: ['Grilled Cheese',3],
av: ['Grilled Chicken',3.5],
aw: ['Hamburger',3.75],
ax: ['Hot Dog',2.25],
ay: ['Individual Pizza',4],
az: ['Large Salad',5.5],
aaa: ['Mac & Cheese',3],
aab: ['Muffin',2.25],
aac: ['Nachos El Grande',5],
aad: ['Noodles',3],
aae: ['Oatmeal',2],
aaf: ['Omelet',3.5],
aag: ['Pancake',1.55],
aah: ['Panini',5.25],
aai: ['Pasta with Sauce',3.5],
aaj: ['Pizza',3.5],
aak: ['Pretzel Roll Sandwich',5.25],
aal: ['Scone',2],
aam: ['Scrambled Eggs',1.25],
//aan: ['Signature Sushi',10],
aao: ['Simple Sandwich',3.5],
aap: ['Small Salad',3],
aaq: ['Soup',3],
aar: ['Spicy Chicken',3.5],
aas: ['Stir Fry',5.25],
//aat: ['Sushi (Select)',12],
//aau: ['Sushi (Traditional)',10],
//aav: ['Sushi (Veggie)',6.5],
aaw: ['Taco Salad',5.5],
//aax: ['Traditional Sushi',8],
aay: ['Turkey Sandwich',4.75],
aaz: ['Veggie Burger',3.5],
aba: ['Waffle',1.25],
abb: ['Wrap',4],
ca: ['Bacon',2],
cb: ['Cinnamon Roll',2.5],
cc: ['Cream Cheese',0.75],
cd: ['Hard Boiled Egg',1.25],
ce: ['Hasbrown',1],
cf: ['Sausage',1],
cg: ['Chips & Guac/Salsa',3],
ch: ['Crackers',0.15],
ci: ['Egg Roll',1.5],
cj: ['Fries',2.1],
ck: ['Guacamole',1],
cl: ['Guacamole Cup',3.5],
cm: ['Mozz Sticks',3.5],
cn: ['Nachos with Cheese',3.5],
co: ['Onion Rings',2],
cp: ['Pop Tart',1.5],
cq: ['Popcorn Chicken',3.5],
cr: ['Special Fries',2],
cs: ['Spring Rolls',4.5],
ct: ['Welches',1.5],
cu: ['Whole Fruit',0.75],
cv: ['Chicken Wings',2.25],
cw: ['Bosco Sticks',2.75],
da: ['Bagged Chips',1.5],
db: ['Brownie',2],
dc: ['Cake Slice',3],
dd: ['Candy',1.6],
de: ['Cereal Cup',2],
df: ['Cheese & Crackers',3],
dg: ['Cheese Cup',0.5],
dh: ['Cheese Its',1.5],
di: ['Churro',1.5],
dj: ['Cliff Bar',2.75],
dk: ['Cookie Large',1.6],
dl: ['Dessert Parfait',2.25],
dm: ['Fruit Cup',2.25],
dn: ['Goldfish',1.5],
dnn: ['Greek Yogurt',2.25],
dp: ['Gummie Candy',2.25],
dq: ['Housemade Chips',1],
dr: ['Hummus',3.5],
ds: ['Ice Cream',3],
dt: ['Jello',1.5],
du: ['Kind Bars',2.75],
dv: ['Oreo',1.5],
dw: ['PB&J',2],
dx: ['Pie Slice',3],
dy: ['Pringles',1.5],
dz: ['Pudding Parfait',2.25],
daa: ['Rice Krispy',2],
dab: ['Soft Pretzel',2.25],
dac: ['String Cheese',1],
dad: ['Chobani Yogurt',2.25],
dae: ['Yogurt Cup',1.75],
daf: ['Yogurt Parfait',3.25],
dag: ['Chicken Tender (3)',3.75],
dah: ['Nutella Sandwich',3],
dai: ['Pop Tart',1.5],
abc: ['Pasta Special',4.5],
abd: ['Crust Special',4.25],
abe: ['Daily Special',5.5],
abf: ['Grill Special',4.5],
abg: ['Picante Special',5]
}

let list = [];